queue_rules:
  - name: aaaaaaa
    batch_size: 12
pull_request_rules:
  - name: Make sure PR are almost up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      update:
  - name: Make sure PR are almost up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions:
      - "#commits-behind >= 10"
    actions:
      update:
  - name: Notify when a PR is removed from the queue
    description: Notify the PR author when its pull request is removed from the merge queue.
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the
          following reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio
          requeue` if you think this was a mistake.
  - name: Request review from team
    description: Request review from a specific team when checks are green.
    conditions:
      - -closed
      - "#approved-reviews-by = 0"
      - "#changes-requested-reviews-by = 0"
      - review-requested != @TEAM_NAME_HERE
    actions:
      request_reviews:
        teams:
          - TEAM_NAME_HERE
